"""
Recommendation Agent (Unimplemented Scaffold).

STATUS: NOT IMPLEMENTED.
This agent stub is a Sprint-3 planning scaffold and is NOT the active
recommendation system. The actual recommendation generation is performed by
RecommendationEngine (ai/engines/recommendation_engine.py), which is wired
into RiskIntelligencePipeline and serves GET /api/v1/risk/recommendations/.

DO NOT confuse this agent stub with RecommendationEngine.
DO NOT remove this file — it is referenced in Sprint planning documents.
"""
from typing import Any, Dict
from ai.agents.base_agent import BaseAgent


class RecommendationAgent(BaseAgent):
    """
    Unimplemented placeholder.
    Real recommendations are generated by ai/engines/recommendation_engine.py.
    """

    @property
    def name(self) -> str:
        return "RecommendationAgent"

    async def run(self, state: Dict[str, Any]) -> Dict[str, Any]:
        # MEDIUM-2: Removed silent empty-list emit from stub.
        # An unimplemented agent must not return fabricated (empty) results.
        raise NotImplementedError(
            "RecommendationAgent is an unimplemented scaffold. "
            "Use RecommendationEngine / GET /api/v1/risk/recommendations/{borrower_id} instead."
        )
